Create deploy.yml
systelab/java-report-test-utilities pull request #3
Opened 2022-01-27 09:45 UTC by gmartinez3werfen

Adds deploy action

2022-01-27 10:19 UTC, alfonsserra commented on .github/workflows/deploy.yml
> +      # Runs a set of commands using the runners shell
???

2022-01-31 08:49 UTC, joaquimvila requested changes

2022-01-31 08:49 UTC, joaquimvila commented on .github/workflows/deploy.yml
> +        run: echo Hello, world!
It looks like if this is just a default template for an action. Why not taking the one of the java-report-generator as a reference?

2022-01-31 11:34 UTC, closed without merging

2022-01-31 11:35 UTC, gmartinez3werfen commented
Closed PR